# -*- coding: utf-8 -*-
"""Collecting_job_data_using_APIs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13vYVMGCJVbhDPeC6dUsEWp6K4vG8BxwP
"""

#Import required libraries
import json
import requests
import pandas as pd
from openpyxl import Workbook

# Data source provided by IBM Data Analyst Professional Certificate
api_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/module%201/Accessing%20Data%20Using%20APIs/jobs.json"

#Define function for data extraction

def get_number_of_jobs_T(technology):

  # Send HTTP GET request
  response = requests.get(api_url)

  # Check if the request was successful
  if response.status_code == 200:
     data = response.json()
     search_term = technology.lower()
     number_of_jobs = 0
     for job in data:
          if "Key Skills" in job and job["Key Skills"] is not None:
              skills = job["Key Skills"].lower()
              if search_term in skills:
                  number_of_jobs += 1
     return technology, number_of_jobs
  else:
     print(f"Failed to fetch data. Status code: {response.status_code}")
     return technology, 0

# Test the function: get_number_of_jobs_T("Python")

#Define function for data extraction
 def get_number_of_jobs_L(location):

    # Send HTTP GET request
    response = requests.get(api_url)
    # Check if the request was successful
    if response.status_code == 200:
     data = response.json()
     search_loc =location.lower()
     number_of_jobs = 0
     for job in data:
         if "Location" in job and job["Location"] is not None:
             job_location = job["Location"].lower()
             if search_loc in job_location:
                 number_of_jobs += 1
     return location,number_of_jobs
    else:
     print(f"Failed to fetch data. Status code: {response.status_code}")
     return technology, 0

# Test the function: get_number_of_jobs_L("Los Angeles")

#Create target skills and locations lists
skills_list =[
             "C", "C#", "C++", "Java", "JavaScript", "Python", "Scala", "Oracle",
              "SQL Server", "MySQL Server", "PostgreSQL", "MongoDB"
              ]
locations_list =[
                "Los Angeles", "New York", "San Francisco", "Washington DC",
                "Seattle", "Austin", "Detroit"
                ]

# Collect skill data
skill_data = []
for tech in skills_list:
    tech_name, count = get_number_of_jobs_T(tech)
    skill_data.append({"Skills": tech_name, "Job Count": count})

df_skills = pd.DataFrame(skill_data).sort_values(by="Job Count",
                          ascending=False).reset_index(drop=True)


# Collect location data
location_data = []
for location in locations_list:
    loc_name, count = get_number_of_jobs_L(location)
    location_data.append({"Location": loc_name, "Job Count": count})

df_locations = pd.DataFrame(location_data).sort_values(by="Job Count",
                                ascending=False).reset_index(drop=True)
print(df_skills)
print(df_locations)

# Save dataframes to individual CSV files
df_skills.to_csv("job_skills.csv", index=False)
df_locations.to_csv("job_locations.csv", index=False)
print("CSV files saved successfully!")

# Create an Excel workbook

# Create a workbook object
wb = Workbook()
ws = wb.active
ws.title = "Skills Analysis"
ws.append(["Skills", "Job Count"])  # Add headers

# Collect and write skills data directly to Excel
for tech in skills_list:
    tech_name, count = get_number_of_jobs_T(tech)
    ws.append([tech_name, count])

# Save the final workbook
wb.save("job_market_skills.xlsx")
print("Excel file saved successfully!")

"""<!--| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2022-01-19        | 0.3     | Lakshmi Holla        | Added changes in the markdown      |
| 2021-06-25        | 0.2     | Malika            | Updated GitHub job json link       |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |--!>

"""